cpp = g++
options = -o ram1 -std=c++11
options1 = -o ram3_128 -std=c++11
options2 = -o ram3_256 -std=c++11
options3 = -o ram3_128_32 -std=c++11
options4 = -o ram3_128_4 -std=c++11
ram: ram1.cpp
	$(cpp) -g ram1.cpp $(options)

ram3_128: ram3_128
	$(cpp) -g ram3_128.cpp $(options1)

ram3_256: ram3_256
	$(cpp) -g ram3_256.cpp $(options2)

ram3_128_32: ram3_128_32
	$(cpp) -g ram3_128_32.cpp $(options3)

ram3_128_4: ram3_128_4
	$(cpp) -g ram3_128_32.cpp $(options4)
